# Generated by Django 3.1.4 on 2022-10-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'فعالیت ها',
                'verbose_name_plural': 'فعالیت ها',
            },
        ),
    ]
