# Generated by Django 3.1.4 on 2022-10-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_activities_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activities',
        ),
    ]
