# Generated by Django 3.1.4 on 2022-10-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_delete_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='about_us_text',
            field=models.TextField(null=True, verbose_name='متن درباره ما سایت'),
        ),
        migrations.AddField(
            model_name='slider',
            name='site_name',
            field=models.CharField(max_length=200, null=True, verbose_name='نام سایت'),
        ),
    ]
