# Generated by Django 3.1.4 on 2022-10-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_auto_20221029_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('url_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان لینک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/sliders', verbose_name='تصویر اسلایدر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'بهترین ویژگی ها',
                'verbose_name_plural': 'بهترین ویژگی ها',
            },
        ),
    ]
