# Generated by Django 3.1.4 on 2022-10-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0008_bestfeatures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestFeatures',
        ),
    ]
