# Generated by Django 3.1.4 on 2022-10-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0011_auto_20221031_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='introducesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/blog', verbose_name='تصویر معرفی'),
        ),
    ]
