# Generated by Django 3.1.4 on 2022-10-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0013_cooperating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.TextField(max_length=2000, verbose_name='زیر عنوان')),
                ('short_txt', models.TextField(max_length=2000, verbose_name='متن کوتاه')),
                ('service_title', models.CharField(max_length=200, verbose_name='عنوان خدمات')),
                ('service_txt', models.TextField(max_length=2000, verbose_name='متن خدمات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/services', verbose_name='تصویر معرفی')),
                ('url_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان لینک')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cooperating',
            options={'verbose_name': 'همکاری', 'verbose_name_plural': 'همکاری'},
        ),
    ]
