# Generated by Django 3.1.4 on 2022-10-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0014_auto_20221031_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'خدمات', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.AlterField(
            model_name='services',
            name='subtitle',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='زیر عنوان'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان'),
        ),
    ]
