# Generated by Django 3.1.4 on 2022-10-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0015_auto_20221031_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='short_txt',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='متن کوتاه'),
        ),
    ]
