# Generated by Django 3.1.4 on 2022-11-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0016_auto_20221031_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acordeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان آموزش')),
                ('text', models.TextField(null=True, verbose_name='سرفصل های دوره')),
            ],
            options={
                'verbose_name': 'آموزش اتوماسیون صنعتی',
                'verbose_name_plural': 'آموزش اتوماسیون صنعتی',
            },
        ),
    ]
