# Generated by Django 3.1.4 on 2022-11-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0017_acordeon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acordeon',
        ),
    ]
