# Generated by Django 3.1.4 on 2022-11-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0019_auto_20221101_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acordeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان آکاردئون')),
                ('text', models.TextField(null=True, verbose_name='متن آکاردئون')),
            ],
            options={
                'verbose_name': 'آکاردئون دپارتمان ها',
                'verbose_name_plural': 'آکاردئون دپارتمان ها',
            },
        ),
    ]
