# Generated by Django 3.1.4 on 2022-11-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0021_auto_20221101_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheBestActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=300, verbose_name='عنوان کوتاه')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('text', models.TextField(null=True, verbose_name='متن آکاردئون')),
            ],
            options={
                'verbose_name': 'بهترین فعالیت ها',
                'verbose_name_plural': 'بهترین فعالیت ها',
            },
        ),
        migrations.DeleteModel(
            name='Acordeon',
        ),
    ]
