# Generated by Django 3.1.4 on 2022-11-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_training', '0002_robotreadmore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RobotReadMore',
        ),
    ]
