# Generated by Django 3.1.4 on 2022-11-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_training', '0007_remove_robot_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='url',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='url_title',
        ),
    ]
