# Generated by Django 3.1.4 on 2022-11-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_training', '0009_robotreadmore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robotreadmore',
            options={'verbose_name': 'بیشتر بدانید اسلایدر', 'verbose_name_plural': 'بیشتر بدانید اسلایدر'},
        ),
        migrations.AddField(
            model_name='robotreadmore',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک'),
        ),
        migrations.AddField(
            model_name='robotreadmore',
            name='url_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان لینک'),
        ),
    ]
