# Generated by Django 3.1.4 on 2022-11-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_training', '0010_auto_20221117_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotreadmore',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/robots', verbose_name='تصویر'),
        ),
    ]
